# Site settings
title: Bhushan Shah
email: bhush94@gmail.com
description: "Yet another (undefined)"
baseurl: ""
url: "https://blog.bshah.in"
github_username:  bhush9

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/
