name: Bhushan Shah
url: http://bhush9.github.io
description: Yet another (undefined)

permalink: /:year/:month/:day/:title/
paginate: 10
pygments: true
markdown: kramdown

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
